# Creado por Alvaro Araya 2020-05-02
# Modificado por Alejandro Araya 2022-02-25
# Revisión 1.1

version: '3.8'

services:
  ## POSTGRESQL ##
  postgres:
    container_name: postgres_container_kc_tg_bot
    image: postgres
    environment:
      POSTGRES_USER: kc_tg_bot_admin
      POSTGRES_PASSWORD: BCdyMaJYELAKCapWU2XU
      POSTGRES_DB: kc_tg_bot
    ports:
      - "5432:5432"
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/'
    networks:
      - kc_tg_bot
    restart: always

  ## KEYCLOAK ##
  keycloak:
    container_name: keycloak_container_kc_tg_bot
    image: jboss/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres_container_kc_tg_bot
      DB_PORT: 5432
      DB_DATABASE: kc_tg_bot
      DB_SCHEMA: public
      DB_USER: kc_tg_bot_admin
      DB_PASSWORD: BCdyMaJYELAKCapWU2XU
      KEYCLOAK_USER: kc_admin
      KEYCLOAK_PASSWORD: BCdyMaJYELAKCapWU2XU
      # JDBC_PARAMS: "ssl=true"
    ports:
      - '9999:8080'
    networks:
      - kc_tg_bot
    restart: always

networks:
  kc_tg_bot:
    driver: bridge

volumes:
  postgres-data:
    driver: local